@echo off
call copy_Brevitee.Full.cmd 
call copy_Brevitee.cmd 
call copy_Brevitee.CommandLine.cmd 
call copy_Brevitee.Data.cmd
call copy_Brevitee.Incubation.cmd 
call copy_Brevitee.Logging.cmd 
call copy_Brevitee.Users.cmd 
call copy_Brevitee.ServiceProxy.cmd 
call copy_Brevitee.Testing.cmd 
