call %HOMEPATH%\Brevitee.cmd
copy /Y %Brevitee%\Brevitee\Brevitee.Analytics\bin\Debug\Brevitee.Analytics.dll .\Root\lib\net40\Brevitee.Analytics.dll
copy /Y %Brevitee%\Brevitee\Brevitee.CommandLine\bin\Debug\Brevitee.CommandLine.dll .\Root\lib\net40\Brevitee.CommandLine.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Data\bin\Debug\Brevitee.Data.dll .\Root\lib\net40\Brevitee.Data.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Data.MsSql\bin\Debug\Brevitee.Data.MsSql.dll .\Root\lib\net40\Brevitee.Data.MsSql.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Data.Schema\bin\Debug\Brevitee.Data.Schema.dll .\Root\lib\net40\Brevitee.Data.Schema.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Data.SQLite\bin\Debug\Brevitee.Data.SQLite.dll .\Root\lib\net40\Brevitee.Data.SQLite.dll
copy /Y %Brevitee%\Brevitee\Brevitee\bin\Debug\Brevitee.dll .\Root\lib\net40\Brevitee.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Drawing\bin\Debug\Brevitee.Drawing.dll .\Root\lib\net40\Brevitee.Drawing.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Dust\bin\Debug\Brevitee.Dust.dll .\Root\lib\net40\Brevitee.Dust.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Html\bin\Debug\Brevitee.Html.dll .\Root\lib\net40\Brevitee.Html.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Incubation\bin\Debug\Brevitee.Incubation.dll .\Root\lib\net40\Brevitee.Incubation.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Javascript\bin\Debug\Brevitee.Javascript.dll .\Root\lib\net40\Brevitee.Javascript.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Profiguration\bin\Debug\Brevitee.Profiguration.dll .\Root\lib\net40\Brevitee.Profiguration.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Schema.Org\bin\Debug\Brevitee.Schema.Org.dll .\Root\lib\net40\Brevitee.Schema.Org.dll
copy /Y %Brevitee%\Brevitee\Brevitee.ServiceProxy\bin\Debug\Brevitee.ServiceProxy.dll .\Root\lib\net40\Brevitee.ServiceProxy.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Syndication\bin\Debug\Brevitee.Syndication.dll .\Root\lib\net40\Brevitee.Syndication.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Logging\bin\Debug\Brevitee.Logging.dll .\Root\lib\net40\Brevitee.Logging.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Management\bin\Debug\Brevitee.Management.dll .\Root\lib\net40\Brevitee.Management.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Testing\bin\Debug\Brevitee.Testing.dll .\Root\lib\net40\Brevitee.Testing.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Yaml\bin\Debug\Brevitee.Yaml.dll .\Root\lib\net40\Brevitee.Yaml.dll
copy /Y %Brevitee%\Brevitee\DaoRef\bin\Debug\DaoRef.dll .\Root\lib\net40\DaoRef.dll

copy /Y %Brevitee%\Brevitee\Brevitee.Analytics\bin\Debug\Brevitee.Analytics.dll .\Root\lib\net45\Brevitee.Analytics.dll
copy /Y %Brevitee%\Brevitee\Brevitee.CommandLine\bin\Debug\Brevitee.CommandLine.dll .\Root\lib\net45\Brevitee.CommandLine.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Data\bin\Debug\Brevitee.Data.dll .\Root\lib\net45\Brevitee.Data.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Data.MsSql\bin\Debug\Brevitee.Data.MsSql.dll .\Root\lib\net45\Brevitee.Data.MsSql.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Data.Schema\bin\Debug\Brevitee.Data.Schema.dll .\Root\lib\net45\Brevitee.Data.Schema.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Data.SQLite\bin\Debug\Brevitee.Data.SQLite.dll .\Root\lib\net45\Brevitee.Data.SQLite.dll
copy /Y %Brevitee%\Brevitee\Brevitee\bin\Debug\Brevitee.dll .\Root\lib\net45\Brevitee.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Drawing\bin\Debug\Brevitee.Drawing.dll .\Root\lib\net45\Brevitee.Drawing.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Dust\bin\Debug\Brevitee.Dust.dll .\Root\lib\net45\Brevitee.Dust.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Html\bin\Debug\Brevitee.Html.dll .\Root\lib\net45\Brevitee.Html.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Incubation\bin\Debug\Brevitee.Incubation.dll .\Root\lib\net45\Brevitee.Incubation.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Javascript\bin\Debug\Brevitee.Javascript.dll .\Root\lib\net45\Brevitee.Javascript.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Profiguration\bin\Debug\Brevitee.Profiguration.dll .\Root\lib\net45\Brevitee.Profiguration.dll
copy /Y %Brevitee%\Brevitee\Brevitee.ServiceProxy\bin\Debug\Brevitee.ServiceProxy.dll .\Root\lib\net45\Brevitee.ServiceProxy.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Syndication\bin\Debug\Brevitee.Syndication.dll .\Root\lib\net45\Brevitee.Syndication.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Schema.Org\bin\Debug\Brevitee.Schema.Org.dll .\Root\lib\net45\Brevitee.Schema.Org.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Logging\bin\Debug\Brevitee.Logging.dll .\Root\lib\net45\Brevitee.Logging.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Management\bin\Debug\Brevitee.Management.dll .\Root\lib\net45\Brevitee.Management.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Testing\bin\Debug\Brevitee.Testing.dll .\Root\lib\net45\Brevitee.Testing.dll
copy /Y %Brevitee%\Brevitee\Brevitee.Yaml\bin\Debug\Brevitee.Yaml.dll .\Root\lib\net45\Brevitee.Yaml.dll
copy /Y %Brevitee%\Brevitee\DaoRef\bin\Debug\DaoRef.dll .\Root\lib\net45\DaoRef.dll

copy /Y %Brevitee%\Brevitee\Brevitee.Analytics\bin\Debug\Brevitee.Analytics.xml .\Root\lib\net40\Brevitee.Analytics.xml
copy /Y %Brevitee%\Brevitee\Brevitee.CommandLine\bin\Debug\Brevitee.CommandLine.xml .\Root\lib\net40\Brevitee.CommandLine.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Data\bin\Debug\Brevitee.Data.xml .\Root\lib\net40\Brevitee.Data.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Data.MsSql\bin\Debug\Brevitee.Data.MsSql.xml .\Root\lib\net40\Brevitee.Data.MsSql.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Data.Schema\bin\Debug\Brevitee.Data.Schema.xml .\Root\lib\net40\Brevitee.Data.Schema.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Data.SQLite\bin\Debug\Brevitee.Data.SQLite.xml .\Root\lib\net40\Brevitee.Data.SQLite.xml
copy /Y %Brevitee%\Brevitee\Brevitee\bin\Debug\Brevitee.xml .\Root\lib\net40\Brevitee.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Drawing\bin\Debug\Brevitee.Drawing.xml .\Root\lib\net40\Brevitee.Drawing.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Dust\bin\Debug\Brevitee.Dust.xml .\Root\lib\net40\Brevitee.Dust.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Html\bin\Debug\Brevitee.Html.xml .\Root\lib\net40\Brevitee.Html.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Incubation\bin\Debug\Brevitee.Incubation.xml .\Root\lib\net40\Brevitee.Incubation.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Javascript\bin\Debug\Brevitee.Javascript.xml .\Root\lib\net40\Brevitee.Javascript.xml
copy /Y %Brevitee%\Brevitee\Brevitee.ServiceProxy\bin\Debug\Brevitee.ServiceProxy.xml .\Root\lib\net40\Brevitee.ServiceProxy.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Syndication\bin\Debug\Brevitee.Syndication.xml .\Root\lib\net40\Brevitee.Syndication.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Schema.Org\bin\Debug\Brevitee.Schema.Org.xml .\Root\lib\net40\Brevitee.Schema.Org.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Logging\bin\Debug\Brevitee.Logging.xml .\Root\lib\net40\Brevitee.Logging.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Management\bin\Debug\Brevitee.Management.xml .\Root\lib\net40\Brevitee.Management.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Testing\bin\Debug\Brevitee.Testing.xml .\Root\lib\net40\Brevitee.Testing.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Yaml\bin\Debug\Brevitee.Yaml.xml .\Root\lib\net40\Brevitee.Yaml.xml
copy /Y %Brevitee%\Brevitee\DaoRef\bin\Debug\DaoRef.xml .\Root\lib\net40\DaoRef.xml

copy /Y %Brevitee%\Brevitee\Brevitee.Analytics\bin\Debug\Brevitee.Analytics.xml .\Root\lib\net45\Brevitee.Analytics.xml
copy /Y %Brevitee%\Brevitee\Brevitee.CommandLine\bin\Debug\Brevitee.CommandLine.xml .\Root\lib\net45\Brevitee.CommandLine.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Data\bin\Debug\Brevitee.Data.xml .\Root\lib\net45\Brevitee.Data.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Data.MsSql\bin\Debug\Brevitee.Data.MsSql.xml .\Root\lib\net45\Brevitee.Data.MsSql.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Data.Schema\bin\Debug\Brevitee.Data.Schema.xml .\Root\lib\net45\Brevitee.Data.Schema.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Data.SQLite\bin\Debug\Brevitee.Data.SQLite.xml .\Root\lib\net45\Brevitee.Data.SQLite.xml
copy /Y %Brevitee%\Brevitee\Brevitee\bin\Debug\Brevitee.xml .\Root\lib\net45\Brevitee.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Drawing\bin\Debug\Brevitee.Drawing.xml .\Root\lib\net45\Brevitee.Drawing.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Dust\bin\Debug\Brevitee.Dust.xml .\Root\lib\net45\Brevitee.Dust.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Html\bin\Debug\Brevitee.Html.xml .\Root\lib\net45\Brevitee.Html.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Incubation\bin\Debug\Brevitee.Incubation.xml .\Root\lib\net45\Brevitee.Incubation.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Javascript\bin\Debug\Brevitee.Javascript.xml .\Root\lib\net45\Brevitee.Javascript.xml
copy /Y %Brevitee%\Brevitee\Brevitee.ServiceProxy\bin\Debug\Brevitee.ServiceProxy.xml .\Root\lib\net45\Brevitee.ServiceProxy.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Syndication\bin\Debug\Brevitee.Syndication.xml .\Root\lib\net45\Brevitee.Syndication.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Schema.Org\bin\Debug\Brevitee.Schema.Org.xml .\Root\lib\net45\Brevitee.Schema.Org.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Logging\bin\Debug\Brevitee.Logging.xml .\Root\lib\net45\Brevitee.Logging.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Management\bin\Debug\Brevitee.Management.xml .\Root\lib\net45\Brevitee.Management.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Testing\bin\Debug\Brevitee.Testing.xml .\Root\lib\net45\Brevitee.Testing.xml
copy /Y %Brevitee%\Brevitee\Brevitee.Yaml\bin\Debug\Brevitee.Yaml.xml .\Root\lib\net45\Brevitee.Yaml.xml
copy /Y %Brevitee%\Brevitee\DaoRef\bin\Debug\DaoRef.xml .\Root\lib\net45\DaoRef.xml