@echo off
call copy_Brevitee.cmd 
call copy_Brevitee.Analytics.cmd
call copy_Brevitee.Automation.cmd
call copy_Brevitee.CommandLine.cmd 
call copy_Brevitee.Data.cmd
call copy_Brevitee.Distributed.cmd
call copy_Brevitee.Drawing.cmd
call copy_Brevitee.Dust.cmd
call copy_Brevitee.Encryption.cmd
call copy_Brevitee.Html.cmd
call copy_Brevitee.Incubation.cmd 
call copy_Brevitee.Javascript.cmd
call copy_Brevitee.Logging.cmd 
call copy_Brevitee.Management.cmd
call copy_Brevitee.Messaging.cmd
call copy_Brevitee.Net.cmd
call copy_Brevitee.Profiguration.cmd
call copy_Brevitee.Schema.Org.cmd
call copy_Brevitee.Server.cmd 
call copy_Brevitee.ServiceProxy.cmd 
call copy_Brevitee.SourceControl.cmd
call copy_Brevitee.Syndication.cmd
call copy_Brevitee.Testing.cmd 
call copy_Brevitee.UserAccounts.cmd 
call copy_Brevitee.Yaml.cmd 

