@echo off
call push_Brevitee.cmd 
call push_Brevitee.CommandLine.cmd 
call push_Brevitee.Data.cmd
call push_Brevitee.Distributed.cmd
call push_Brevitee.Encryption.cmd
call push_Brevitee.Html.cmd
call push_Brevitee.Incubation.cmd 
call push_Brevitee.Javascript.cmd
call push_Brevitee.Logging.cmd 
call push_Brevitee.Management.cmd
call push_Brevitee.Net.cmd
call push_Brevitee.Profiguration.cmd
call push_Brevitee.Schema.Org.cmd
call push_Brevitee.ServiceProxy.cmd 
call push_Brevitee.Testing.cmd 
call push_Brevitee.UserAccounts.cmd 