attrib -R .\Brevitee\Brevitee.nuspec
attrib -R .\Brevitee.Analytics\Brevitee.Analytics.nuspec
attrib -R .\Brevitee.Automation\Brevitee.Automation.nuspec
attrib -R .\Brevitee.CommandLine\Brevitee.CommandLine.nuspec
attrib -R .\Brevitee.Data\Brevitee.Data.nuspec
attrib -R .\Brevitee.Distributed\Brevitee.Distributed.nuspec
attrib -R .\Brevitee.Drawing\Brevitee.Drawing.nuspec
attrib -R .\Brevitee.Dust\Brevitee.Dust.nuspec
attrib -R .\Brevitee.Encryption\Brevitee.Encryption.nuspec
attrib -R .\Brevitee.Html\Brevitee.Html.nuspec
attrib -R .\Brevitee.Incubation\Brevitee.Incubation.nuspec
attrib -R .\Brevitee.Javascript\Brevitee.Javascript.nuspec
attrib -R .\Brevitee.Logging\Brevitee.Logging.nuspec
attrib -R .\Brevitee.Management\Brevitee.Management.nuspec
attrib -R .\Brevitee.Messaging\Brevitee.Messaging.nuspec
attrib -R .\Brevitee.Net\Brevitee.Net.nuspec
attrib -R .\Brevitee.Profiguration\Brevitee.Profiguration.nuspec
attrib -R .\Brevitee.Schema.Org\Brevitee.Schema.Org.nuspec
attrib -R .\Brevitee.Server\Brevitee.Server.nuspec
attrib -R .\Brevitee.ServiceProxy\Brevitee.ServiceProxy.nuspec
attrib -R .\Brevitee.SourceControl\Brevitee.SourceControl.nuspec
attrib -R .\Brevitee.Syndication\Brevitee.Syndication.nuspec
attrib -R .\Brevitee.Testing\Brevitee.Testing.nuspec
attrib -R .\Brevitee.UserAccounts\Brevitee.UserAccounts.nuspec
attrib -R .\Brevitee.Yaml\Brevitee.Yaml.nuspec
